### ISSUE TITLE
Which Filament for printing / Contact ? 

### ISSUE THREAD

**Issue by moelski** [martinbudden/BabyCube#3]
Hi Martin, 

this is not an issue. It's more two first questions before I start the build :-)

Which Filament did you use for printing the body structure? PLA / ABS / ??
And how much infill did you use? 

The other question is to get in contact with you. I would love to make some YT videos with the build of this printer. 
Is there any way to get in contact with you on a more direct way like mail / WhatsApp or something like that? 
If you like, you can contact me via mail : dominik@drklipper.de

But anyway ... thank you for this awesome project !

Dominik

**Comment by martinbudden** [comment]
See https://github.com/martinbudden/BabyCube/tree/main/BC200#tips-for-printing-the-parts - a filament with a high glass transition temperature (ie ABS or PETG) should be used. PLA should not be used, since parts of the printer can get hot enough to cause PLA to soften and bend. Note also the instructions on power management, fans and configuring the printer.
